<?
if(! defined('BASEPATH') ){ exit('Unable to view file.'); }

$mesaj = '';
if(isset($_POST['submit'])){
	$posts = $db->EscapeString($_POST['set']);
	foreach ($posts as $key => $value){
		if($site[$key] != $value){
			$db->Query("UPDATE `site_config` SET `config_value`='".$value."' WHERE `config_name`='".$key."'");
			$site[$key] = $value;
		}
	}
	
	$mesaj = '<div class="alert success"><span class="icon"></span><strong>Success!</strong> Settings successfully changed</div>';
}
if(isset($_POST['usubmit'])){
	$posts = $db->EscapeString($_POST['set2']);
	foreach ($posts as $key => $value){
		if($site[$key] != $value){
			if($key == 'ref_sale'){
				$value = ($value > 100 ? 100 : ($value < 0 ? 0 : $value));
			}

			$db->Query("UPDATE `site_config` SET `config_value`='".$value."' WHERE `config_name`='".$key."'");
			$site[$key] = $value;
		}
	}
	
	$mesaj = '<div class="alert success"><span class="icon"></span><strong>Success!</strong> Settings successfully changed</div>';
}
?>
<section id="content" class="container_12 clearfix"><?=$mesaj?>
	<div class="grid_6">
		<form method="post" class="box">
			<div class="header">
				<h2>General Settings</h2>
			</div>
			<div class="content">
				<div class="row">
					<label><strong>Referrals System</strong><small>Allow users to invite other persons?</small></label>
					<div><select name="set[refsys]"><option value="0">Disabled</option><option value="1"<?=($site['refsys'] != 0 ? ' selected' : '')?>>Enabled</option></select></div>
				</div>
				<div class="row">
					<label><strong>Payments System</strong><small>Pay money for referrals?</small></label>
					<div><select name="set[paysys]"><option value="0">Disabled</option><option value="1"<?=($site['paysys'] != 0 ? ' selected' : '')?>>Enabled</option></select></div>
				</div>
			</div>
			<div class="actions">
				<div class="right">
					<input type="submit" value="Submit" name="submit" />
				</div>
			</div>
		</form>
	</div>
	<div class="grid_6">
		<form method="post" class="box">
			<div class="header">
				<h2>Other Settings</h2>
			</div>
			<div class="content">
				<div class="row">
					<label><strong>Coins per Referral</strong></label>
					<div><input type="text" name="set2[ref_coins]" value="<?=$site['ref_coins']?>" required /></div>
				</div>
				<div class="row">
					<label><strong>Cash per Referral $</strong><small>Revenue for every referral registered</small></label>
					<div><input type="text" name="set2[ref_cash]" value="<?=$site['ref_cash']?>" required /></div>
				</div>
				<div class="row">
					<label><strong>Percent per Sale %</strong><small>Percent from each sale generated by referrals</small></label>
					<div><input type="text" name="set2[ref_sale]" value="<?=$site['ref_sale']?>" maxlength="3" required /></div>
				</div>
				<div class="row">
					<label><strong>Required Clicks for commission</strong><small>How many clicks referral must have, to receive<br /> commission (set 0 to disable)</small></label>
					<div><input type="text" name="set2[aff_click_req]" value="<?=$site['aff_click_req']?>" required /></div>
				</div>
			</div>
			<div class="actions">
				<div class="right">
					<input type="submit" value="Submit" name="usubmit" />
				</div>
			</div>
		</form>
	</div>
</section>